es_config:
  node.name: "elasticdata"
  cluster.name: "go-cluster"
  discovery.seed_hosts: "elasticmaster:9300"
  network.host: 0.0.0.0
  http.port: 9200
  transport.port: 9300
  node.data: true
  node.master: false
  bootstrap.memory_lock: true
  xpack.security.authc.realms.file.file1.order: 0
  xpack.security.authc.realms.native.native1.order: 1

es_user: elasticsearch
es_group: elasticsearch
es_xpack_trial: true
es_enable_http_ssl: true
es_enable_transport_ssl: true

es_ssl_keystore: "files/certs/my-keystore.p12"
es_ssl_keystore_password: "{{vault_es_ssl_keystore_password}}"
es_ssl_truststore: "files/certs/my-truststore.p12"
es_ssl_truststore_password: "{{vault_es_ssl_truststore_password}}"
es_ssl_certificate_authority: "files/certs/my-ca.p12"
es_ssl_certificate_path: "{{ es_conf_dir }}/certs"
es_ssl_verification_mode: "certificate"

es_heap_size: 350m
es_api_basic_auth_username: elastic
es_api_basic_auth_password: "{{vault_es_api_basic_auth_password}}"

es_validate_certs: no
