
es_config:
  node.name: "node1"
  cluster.name: "custom-cluster"
  discovery.seed_hosts: "localhost:9301"
  http.port: 9201
  transport.port: 9301
  node.data: false
  node.master: true
  bootstrap.memory_lock: true
  xpack.security.authc.realms.file.file1.order: 0
  xpack.security.authc.realms.native.native1.order: 1

es_heap_size: 1g
es_api_basic_auth_username: elastic
es_api_basic_auth_password: "{{vault_es_api_basic_auth_password}}"
es_enable_http_ssl: true
es_enable_transport_ssl: true
es_ssl_keystore: "files/certs/my-keystore.p12"
es_ssl_truststore: "files/certs/my-truststore.p12"
es_ssl_keystore_password: "{{vault_es_ssl_keystore_password}}"
es_ssl_truststore_password: "{{vault_es_ssl_truststore_password}}"
es_validate_certs: no